services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LemonMind\MessageBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    LemonMind\MessageBundle\MessageHandler\CreateNotificationMessageHandler:
        tags:
            - { name: messenger.message_handler }
        calls:
            -   setTexter: [ '@?texter' ]
            -   setChatter: [ '@?chatter' ]