services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LemonMind\MessageBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    LemonMind\MessageBundle\MessageHandler\CreateNotificationMessageHandler:
        tags:
            - { name: messenger.message_handler }
        calls:
            -   setTexter: [ '@?texter' ]
            -   setChatter: [ '@?chatter' ]

    #
    # SETTINGS
    #
    LemonMind\MessageBundle\Settings\:
        resource: '../../Settings/*'
        lazy: true

    LemonMind\MessageBundle\Settings\MessageSettings:
        arguments: [ '@parameter_bag' ]